Controllers/FilmesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Data.Entity;
using MVC.Model;

namespace MVC.Controllers
{
    public class FilmesController : Controller
    {
        Contexto contexto = new Contexto();

        // GET: Filmes
        public ActionResult Index()
        {
            List<Filme> lstFilme = contexto.Filmes.ToList();
            return View(lstFilme);
        }

        //get: Filmes/Create
        public ActionResult Create()
        {
            return View();
        }

         //post: Filme/Create
         [HttpPost]
         [ValidateAntiForgeryToken]
         public ActionResult Create([Bind(Include ="id, descricao, sinopse, quantidade")] Filme filme)
     
        {
            if (ModelState.IsValid)
            {
                contexto.Filmes.Add(filme);
                contexto.SaveChanges();
                return RedirectToAction("Index");
            }
            else return View(filme);
        }

        //get: Filmes/Details
        public ActionResult Details(int? id)
        {
            if (id == null)
            
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                Filme filme = contexto.Filmes.Find(id);
            if (filme == null)
                return HttpNotFound();
            return View(filme);

            
        }

        //Post: //Filmes/edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id, descricao, sinopse, quantidade")] Filme filme)
        {
            if (ModelState.IsValid)
            {
                contexto.Entry(filme).State = EntityState.Modified;
                contexto.SaveChanges();
                return RedirectToAction("Index");
            }
            else return View(filme);
        }

        //get: Filmes/Edit
        public ActionResult Edit(int? id)
        {
            if (id == null)

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Filme filme = contexto.Filmes.Find(id);
            if (filme == null)
                return HttpNotFound();
            return View(filme);


        }

        //GET: //Filmes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Filme filme = contexto.Filmes.Find(id);
            if (filme == null)
                return HttpNotFound();
            return View(filme);

        }

        //Post: //Filmes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteCofirme(int id)
        {
            Filme filme = contexto.Filmes.Find(id);
            contexto.Filmes.Remove(filme);
            contexto.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                contexto.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Locadora de Filmes", "Index", "Filmes", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Filmes", "Index", "Filmes")</li>
                    <li>@Html.ActionLink("Clientes", "Index", "Clientes")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Matheus System Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>